use_frameworks!

source 'https://github.com/iOSModularization/AHFMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'AHFMShowPageManger_Example' do
  pod 'AHFMShowPageManger', :path => '../'

  target 'AHFMShowPageManger_Tests' do
    inherit! :search_paths

    
  end
end
